fonts = [
    'Arial, sans-serif', 'Verdana, sans-serif', 'Times New Roman, serif',
    'Georgia, serif', 'Courier New, monospace', 'Lucida Console, monospace',
    'Trebuchet MS, sans-serif', 'Arial Black, sans-serif', 'Comic Sans MS, sans-serif',
    'Impact, sans-serif', 'Lucida Sans Unicode, sans-serif', 'Tahoma, sans-serif',
    'Palatino Linotype, serif', 'Book Antiqua, serif', 'Helvetica, sans-serif',
    'Garamond, serif', 'MS Serif, serif', 'MS Sans Serif, sans-serif',
    'Symbol, sans-serif', 'Webdings, sans-serif', 'Gill Sans, sans-serif',
    'Futura, sans-serif', 'Optima, sans-serif', 'Geneva, sans-serif',
    'Franklin Gothic Medium, sans-serif', 'Century Gothic, sans-serif', 'Candara, sans-serif',
    'Arial Narrow, sans-serif', 'Brush Script MT, cursive', 'Calibri, sans-serif',
    'Cambria, serif', 'Corbel, sans-serif', 'Constantia, serif',
    'Rockwell, serif', 'Perpetua, serif', 'Baskerville, serif',
    'Bodoni MT, serif', 'Didot, serif', 'Hoefler Text, serif',
    'Calisto MT, serif', 'Bookman Old Style, serif', 'Century Schoolbook, serif',
    'Copperplate Gothic Light, serif', 'Old English Text MT, serif', 'Goudy Old Style, serif',
    'Bell MT, serif', 'Mongolian Baiti, serif', 'MT Extra, sans-serif',
    'Monotype Corsiva, cursive', 'Papyrus, fantasy', 'Vivaldi, cursive',
    'Rage Italic, cursive', 'Kristen ITC, cursive', 'Jokerman, fantasy',
    'Algerian, fantasy', 'Chiller, fantasy', 'Broadway, fantasy',
    'Bernard MT Condensed, serif', 'Harrington, serif', 'Brush Script Std, cursive',
    'Gigi, cursive', 'Kunstler Script, cursive', 'Playbill, fantasy',
    'Viner Hand ITC, cursive', 'Snap ITC, fantasy', 'Tempus Sans ITC, sans-serif',
    'Tw Cen MT, sans-serif', 'Wide Latin, serif', 'Berlin Sans FB, sans-serif',
    'Bauhaus 93, sans-serif', 'Lucida Handwriting, cursive', 'Magneto, fantasy',
    'Matura MT Script Capitals, cursive', 'Niagara Engraved, serif', 'Niagara Solid, sans-serif',
    'OCR A Extended, monospace', 'Onyx, serif', 'Parchment, fantasy',
    'Ravie, fantasy', 'Script MT Bold, cursive', 'Showcard Gothic, fantasy',
    'Snap ITC, fantasy', 'Stencil, sans-serif', 'Vladimir Script, cursive',
    'Freestyle Script, cursive', 'Garamond, serif', 'Century, serif',
    'Lucida Bright, serif', 'Lucida Fax, serif', 'Lucida Sans, sans-serif',
    'Lucida Sans Typewriter, monospace', 'Copperplate Gothic Bold, serif', 'Eras Bold ITC, sans-serif',
    'Eras Demi ITC, sans-serif', 'Eras Light ITC, sans-serif', 'Eras Medium ITC, sans-serif',
    'Footlight MT Light, serif', 'Forte, fantasy', 'Franklin Gothic Book, sans-serif',
    'Franklin Gothic Demi, sans-serif', 'Franklin Gothic Demi Cond, sans-serif', 'Franklin Gothic Heavy, sans-serif',
    'Franklin Gothic Medium Cond, sans-serif', 'Garamond, serif', 'Gill Sans MT, sans-serif',
    'Gill Sans MT Condensed, sans-serif', 'Gill Sans MT Ext Condensed Bold, sans-serif', 'Gloucester MT Extra Condensed, sans-serif',
    'Haettenschweiler, sans-serif', 'Harlow Solid Italic, sans-serif', 'Harrington, serif',
    'High Tower Text, serif', 'Imprint MT Shadow, serif', 'Informal Roman, cursive',
    'Kabel Bk BT, sans-serif', 'Kabel Ult BT, sans-serif', 'Kabel, sans-serif',
    'Kino MT, sans-serif', 'Kokonor, sans-serif', 'Latha, sans-serif',
    'Leelawadee, sans-serif', 'Levenim MT, sans-serif', 'LilyUPC, sans-serif',
    'Lucida Calligraphy, cursive', 'Lucida Sans Unicode, sans-serif', 'Mangal, sans-serif',
    'Marlett, sans-serif', 'Microsoft Sans Serif, sans-serif', 'Mistral, cursive',
    'Modern No. 20, serif', 'Mongolian Baiti, serif', 'MS Gothic, sans-serif',
    'MS Mincho, serif', 'MS Outlook, sans-serif', 'MS PGothic, sans-serif',
    'MS PMincho, serif', 'MS Reference Sans Serif, sans-serif', 'MS Reference Specialty, sans-serif',
    'MS UI Gothic, sans-serif', 'MT Extra, sans-serif', 'MV Boli, sans-serif',
    'Narkisim, sans-serif', 'Nyala, sans-serif', 'Palace Script MT, cursive',
    'PMingLiU, serif', 'Raavi, sans-serif', 'Rod, sans-serif',
    'Script MT Bold, cursive', 'Shruti, sans-serif', 'SimSun, serif',
    'Sylfaen, serif', 'Symbol, sans-serif', 'Tahoma, sans-serif',
    'Times, serif', 'Trebuchet MS, sans-serif', 'Tunga, sans-serif',
    'Verdana, sans-serif', 'Vijaya, sans-serif', 'Viner Hand ITC, cursive',
    'Vivaldi, cursive', 'Vrinda, sans-serif', 'Webdings, sans-serif',
    'Wingdings, sans-serif', 'Wingdings 2, sans-serif', 'Wingdings 3, sans-serif',
    'Angsana New, sans-serif', 'AngsanaUPC, sans-serif', 'Aparajita, sans-serif',
    'Cordia New, sans-serif', 'CordiaUPC, sans-serif', 'DaunPenh, sans-serif',
    'DilleniaUPC, sans-serif', 'FrankRuehl, serif', 'FreesiaUPC, sans-serif',
    'IrisUPC, sans-serif', 'JasmineUPC, sans-serif', 'KodchiangUPC, sans-serif',
    'LilyUPC, sans-serif', 'Lucida Sans, sans-serif', 'NSimSun, serif',
    'Shruti, sans-serif', 'SimSun, serif', 'Simplified Arabic, sans-serif',
    'Simplified Arabic Fixed, sans-serif', 'Sylfaen, serif', 'Tahoma, sans-serif',
    'Times New Roman, serif', 'Traditional Arabic, sans-serif', 'Trebuchet MS, sans-serif',
    'Tunga, sans-serif', 'Verdana, sans-serif', 'Vijaya, sans-serif',
    'Wingdings, sans-serif', 'Wingdings 2, sans-serif', 'Wingdings 3, sans-serif',
    'Aharoni, sans-serif', 'Andalus, serif', 'Angsana New, sans-serif',
    'AngsanaUPC, sans-serif', 'Aparajita, sans-serif', 'Arabic Typesetting, serif',
    'Batang, serif', 'BatangChe, serif', 'Browallia New, sans-serif',
    'BrowalliaUPC, sans-serif', 'Comic Sans MS, cursive', 'Cordia New, sans-serif',
    'CordiaUPC, sans-serif', 'DaunPenh, sans-serif', 'David, serif',
    'DilleniaUPC, sans-serif', 'Estrangelo Edessa, sans-serif', 'EucrosiaUPC, sans-serif',
    'FrankRuehl, serif', 'FreesiaUPC, sans-serif', 'Gautami, sans-serif',
    'Gisha, sans-serif', 'IrisUPC, sans-serif', 'JasmineUPC, sans-serif',
    'Kartika, sans-serif', 'KodchiangUPC, sans-serif', 'Latha, sans-serif',
    'Levenim MT, sans-serif', 'LilyUPC, sans-serif', 'Malgun Gothic, sans-serif'
]
```
